HEPAddr         = "0.0.0.0:9060"
HEPWorkers      = 100
MQName          = ""
MQAddr          = ""
MQTopic         = ""
PromAddr        = ""
PromTargetIP    = ""
PromTargetName  = ""
DBDriver        = "mysql"
DBAddr          = "localhost:3306"
DBUser          = "root"
DBPass          = ""
DBDataTable     = "homer_data"
DBConfTable     = "homer_configuration"
DBPath          = ""
DBBulk          = 100
DBRotate        = true
DBDropDays      = 0
SentryDSN       = ""
AlegID          = "x-cid"
LogDbg          = ""
LogLvl          = "info"
LogStd          = false
Config          = "./heplify-server.toml"

# Examples:
# -------------------------------------
# DBDriver        = "postgres"
# DBPath          = "/var/lib/postgresql/data/homer"
# PromAddr        = "0.0.0.0:8899"
# PromTargetIP    = "10.1.2.111,10.1.2.4,10.1.2.5,10.1.2.6,10.12.44.222"
# PromTargetName  = "sbc_access,sbc_core,kamailio,asterisk,pstn_gateway"
# SentryDSN       = "https://<key>:<secret>@sentry.io/<project>"
# LogDbg          = "hep,sql"
# LogLvl          = "warning"
