version: '2.2'
services:
  heplify:
    container_name: heplify
    image: qxip/heplify-server:master
    command: "./heplify-server"
    ports:
      - 9060:9060/udp
    container_name: "heplify-server"
    environment:
      - "HEPLIFYSERVER_HEPADDR=0.0.0.0:9060"
      - "HEPLIFYSERVER_HEPWORKERS=100"
      - "HEPLIFYSERVER_DBDRIVER=mysql"
      - "HEPLIFYSERVER_DBADDR=dbmysql:3306"
      - "HEPLIFYSERVER_DBUSER=homer_user"
      - "HEPLIFYSERVER_DBPASS=homer_password"
      - "HEPLIFYSERVER_LOGLVL=info"
      - "HEPLIFYSERVER_LOGSTD=true"
      - "HEPLIFYSERVER_DBBULK=1"
      - "HEPLIFYSERVER_PROMADDR=0.0.0.0:9999"
      - "HEPLIFYSERVER_PROMTARGETIP=127.0.0.1"
      - "HEPLIFYSERVER_PROMTARGETNAME=localhost"
    restart: unless-stopped
    depends_on:
      dbmysql:
         condition: service_healthy

  dbmysql:
    container_name: dbmysql
    image: mysql:5.7
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      - "MYSQL_ROOT_PASSWORD=homer_password"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_ROOT_HOST=%"
    expose:
      - 3306
    ports:
      - 3306:3306
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  homer-webapp:
    container_name: homer-webapp
    image: sipcapture/homer-webapp
    environment:
      - "DB_HOST=dbmysql"
      - "DB_USER=homer_user"
      - "DB_PASS=homer_password"
    ports:
      - "80:80"
    volumes:
      - ./docker-compose.yml:/homer-semaphore/.bootstrapped
    restart: unless-stopped
    depends_on:
      dbmysql:
         condition: service_healthy

  telegraf:
    image: telegraf
#    restart: unless-stopped
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    ports:
      - "8092:8092/udp"
      - "8125:8125/udp"
    depends_on:
      dbmysql:
         condition: service_healthy

  telestats:
    image: qxip/telestats:master
    command: nodejs index.js -c /config.js
    restart: unless-stopped
    volumes:
      - ./telestats.conf:/config.js
    expose:
      - 8094
    ports:
      - "8094:8094/udp"
    depends_on:
      dbmysql:
         condition: service_healthy
    
